# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
